services:
  - type: web
    name: odoo
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        value: odoo-db:5432
      - key: USER
        value: odoo
      - key: PASSWORD
        value: odoo

  - type: web
    name: odoo-db
    env: docker
    plan: free
    dockerfilePath: ./db.Dockerfile
    envVars:
      - key: POSTGRES_DB
        value: odoo
      - key: POSTGRES_USER
        value: odoo
      - key: POSTGRES_PASSWORD
        value: odoo
    autoDeploy: false
